projects:
  Zeller Customers:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: nknbn7ti4neh3g6rwpjqwp6guu
        maxDepth: 2
extensions:
  amplify:
    version: 3
